### PR TITLE
Fix regex matching many characters as possible

### PR DESCRIPTION
**Pull request by kuizuo**
This is my [regex test](https://regexr.com/6q6ih)

regex matches as many characters as possible, Such as

```
<div :class="isDark ? 'dark' : 'light'" />

<div className={isDark" ? 'dark': 'light'} />
```

### CODE REVIEW

**Comment by moalamri** [comment]
Hi @kuizuo 
Thanks for contributing,
In this case what should be the captured group number?
I see that it has 4 groups.

**Comment by kuizuo** [comment]
yes, I think use regex back can more accurate matching. And `+` replace `.*?`

**Comment by moalamri** [comment]
@JasperSurmont
console.log(match);

There are 6 groups,

0: 'class={class is here}'
1: ''
2: 'class'
3: '{'
4: 'class is here'
5: '}'

Could this be easier for parsing with the suggested regex here?

**Comment by JasperSurmont** [comment]
I've started wondering if it would be nice to have some default implemented regex for most use cases, which the user can select (drop down menu for example) and which also provide explanation what it would match.

All the other niche use cases in which the regex has to change a lot is up to the user, because it's impossible (or at least extremely hard) to satisfy every use case with one generic regex

**Comment by moalamri** [comment]
I still vote for specifying the prefix and suffix for matching,
Take this multiline folding extension as example:
https://github.com/zokugun/vscode-explicit-folding

Where settings could look like this:
```json
"inlineFold.rules": {
    "javascriptreact": {
        "pre": "class=",
        "start": "{'",
        "end": "'}"
    }
}
```

`start` and `end` are parts that won't be folded, but what between will get folded what ever character is used in there.
The `pre` character will be useful to specify which attribute to be targeted. Or what markdown formatting to target.

What do you think?

**Comment by JasperSurmont** [comment]
The pre - start - end method is the easiest for the end user. It would still not fix classes like:

**Comment by moalamri** [comment]
> The pre - start - end method is the easiest for the end user. It would still not fix classes like:
> 
> ```
> 
> class=`${foo(`abc${variable}defg`)}`
> 
> ```
> 
> But I think that is not super important
> 
> 
> 
> 
> 
> 

How come does this get even parsed? What framework uses that?

**Comment by moalamri** [comment]
What about if we follow the extension I mentioned above as they use regex for matching, so we used regex for `pre`, `start` and `end` ?

"pre": "(class|className)="
"start": "[`'"{]"
"end": "[^`'"}].*?"

then later `start` and `end` are grouped apart, and we add the group capture id `(\2|})` to become:
`(class|className)=([`'"{])([^`'"}].*?)(\2|})`

**Comment by moalamri** [comment]
@JasperSurmont 

Please have a look here:

https://replit.com/@moalamri/Regex-anatomy#index.ts

Try any concated className value, be sure to escape variables first so it can act as raw text.
There will be cleaner utility to read and fix any regex that needs modifications.

@kuizuo 
The regex will be greedy as you suggested, but in the upcoming update where `start` and `end` are configurable.

**Pull request closed without merging**
