### PR TITLE
Add `diableInDiffEditor` option

### LINKED ISSUE #116: Inline Fold should be disabled when viewing file diff in diff editor
Screenshot 2023-06-14 051528

### PR DESCRIPTION
**Pull request by nix6839**
Resolve #116

### CODE REVIEW

**Comment by moalamri** [comment]
Hey @nix6839 
This is a great workaround 👍🏻 I remember I've looked into VsCode documents and didn't find any API to describe the type of opened editors, so I like your idea of removing decoration from doubled tabs. 
I have noticed that if I go back to the original (non working tree) tab, the contents aren't folded, and they will be folded when I close the diff tab, because they both have same URI.
We could accept this as side-effect of this feature?

**Comment by nix6839** [comment]
@moalamri  I think I've fixed it.
Idea from: https://github.com/usernamehw/vscode-error-lens/issues/72#issuecomment-1062046817B

**Comment by moalamri** [comment]
I thought I would find the solution by `isPreview`, but it didn’t work. Thanks for finding the solution!
I’ll merge and push an update in few days

**Comment by moalamri** [comment]
Hey @nix6839 
Sorry for late, we had 3 days holyday.
I will merge and publish an update.
Thanks

**Pull request merged**
