### PR TITLE
Dev/v0.2.2

### PR DESCRIPTION
**Pull request by moalamri**

### CODE REVIEW

**Review by emedeirox — CHANGES_REQUESTED** [review]
@moalamri  I started to use React some days ago and I found a case that default regex is not capturing. I think need be updated.

```js
<div style={{width:'100%'}}>
```

```
(style)=((({{|{)(`|))|(['"`]))(.*?)(\2|(\5)(}}|}))
g
7
```

**Comment by moalamri** [comment]
This only happens with style attribute? In that case it could be added as an example rather than changing the default regex, what do you think?

**Comment by e-medeiros** [comment]
> This only happens with style attribute? In that case it could be added as an example rather than changing the default regex, what do you think?

It can be done this way.

**Review by emedeirox — APPROVED** [review]

**Comment by moalamri** [comment]
@e-medeiros I was about to add an example 😅 
No worries, we can add the example at any time. I prefer that you make the example PR since you know what it is called in react when object-like are used for style, I've never used react so I can't figure 👯 
Thanks alot

**Pull request merged**
