### PR TITLE
#50 Add Laravel Blade to default settings

### PR DESCRIPTION
**Pull request by e-medeiros**
This solve #50

### CODE REVIEW

**Review by moalamri — CHANGES_REQUESTED** [review]
Awesome,
Could you please add php as well?

**Review by e-medeiros — COMMENTED** [review]
Done.

**Review by e-medeiros — COMMENTED** [review]
By the way I added aswell php twig template, erb (ruby template) and Nunjucks template

**Comment by moalamri** [comment]
Awsome :)
Thank you so much, I will also add a quick feature in the same PR

**Review by moalamri — APPROVED** [review]

**Pull request merged**
